name: build and deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-shopping-cart-12045"
          heroku_email: "shubham.battoo@hotmail.com"